spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boarddb
    username: postgres
    password: 1234d
    driver-class-name: org.postgresql.Driver
    web:
      resources:
        static-locations: classpath:/static/
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    com.study: DEBUG

